### ISSUE TITLE
FATAL: could not prepare query

### ISSUE THREAD

**Issue by moodmosaic** [jcnelson/poxl#3]
As per the README.md instructions under *How to Develop* section:

1. Built `stacks-blockchain` (from `master`, at [26bfd5fcdc](https://github.com/stacks-network/stacks-blockchain/tree/26bfd5fcdc1f25106288f18ced05290b569f6abb) (currently that's the latest commit))
2. Copied `clarity-cli` to `$PATH`
3. Run the tests as follows:

```
$ cd tests/ && ./run-tests.sh

INFO [1654008047.081269] [src/chainstate/stacks/index/file.rs:275] [main] Migrate 0 blocks to external blob storage at /tmp/vm-poxl-test-poxl.clar.db/marf.sqlite.blobs
INFO [1654008047.081308] [src/chainstate/stacks/index/file.rs:204] [main] Preemptively vacuuming the database file to free up space after copying trie blobs to a separate file
FATAL: could not prepare query
Caused by: no such table: cli_chain_tips
```

**Comment by jcnelson** [comment]
Hey @moodmosaic, tanks for your report!  I think that's a bug in `clarity-cli` (part of https://github.com/stacks-network/stacks-blockchain).  ~~I'm going to move this issue there.~~

Can you re-run the command with `BLOCKSTACK_DEBUG=1` and `RUST_BACKTRACE=full` set in the environment, so we can get a stack trace?  Thanks!

EDIT: I can't move it since it's in a different org. Can you re-open over there instead, with the above information?  Thanks!

**Comment by moodmosaic** [comment]
Sure! I'll re-open there, and also include the extra debug info. Thanks for the help 👍

**Comment by moodmosaic** [comment]
@jcnelson, done. https://github.com/stacks-network/stacks-blockchain/issues/3157

**Comment by moodmosaic** [comment]
@jcnelson, if there's some temporary fix I could patch on (locally) just to get the tests to run, that would be great. No rush otherwise. Thank you.
